/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agor_2012 (https://sketchfab.com/Agor_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-man-working-at-a-table-with-a-laptop-be6b2404359c474fb0ed148e1882516e
Title: Low poly man working at a table with a laptop
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ManTypingPc(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '/models/low_poly_man_working_at_a_table_with_a_laptop(1).glb'
  )
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    if (names.length > 0) {
      const action = actions[names[0]]
      action?.reset().fadeIn(0.5).play()
    }
  }, [actions, names])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Empty_1" position={[0, 3, -0.1]}>
                <group name="chair_0" position={[0, -0.9, 0.1]} scale={0.8}>
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['Material.006']}
                  />
                  <mesh
                    name="Object_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['Material.005']}
                  />
                  <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.010']}
                  />
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.003']}
                  />
                </group>
              </group>
              <group name="book_5" position={[-3.5, 4.6, 2.6]} rotation={[0, -0.2, 0]} scale={0.8}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials['Material.016']}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials['Material.015']}
                />
              </group>
              <group name="book2_6" position={[-3.4, 4.4, 2.8]} scale={0.8}>
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials['Material.014']}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials['Material.016']}
                />
              </group>
              <group
                name="laptop_8"
                position={[0.1, 4.4, 3.6]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.2, 0.1, 0.2]}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials['Material.009']}
                />
                <group
                  name="Plane002_7"
                  position={[0, 0.1, -3.6]}
                  rotation={[1.3, 0, 0]}
                  scale={[1, 1, 1.3]}>
                  <mesh
                    name="Object_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Object_20"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials['Material.009']}
                  />
                  <mesh
                    name="Object_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_0}
                  />
                </group>
              </group>
              <group name="Armature_92">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_116"
                    geometry={nodes.Object_116.geometry}
                    material={materials.boots}
                    skeleton={nodes.Object_116.skeleton}
                  />
                  <skinnedMesh
                    name="Object_117"
                    geometry={nodes.Object_117.geometry}
                    material={materials.pants}
                    skeleton={nodes.Object_117.skeleton}
                  />
                  <skinnedMesh
                    name="Object_118"
                    geometry={nodes.Object_118.geometry}
                    material={materials.shirt}
                    skeleton={nodes.Object_118.skeleton}
                  />
                  <skinnedMesh
                    name="Object_119"
                    geometry={nodes.Object_119.geometry}
                    material={materials.skin}
                    skeleton={nodes.Object_119.skeleton}
                  />
                  <skinnedMesh
                    name="Object_120"
                    geometry={nodes.Object_120.geometry}
                    material={materials.mouth}
                    skeleton={nodes.Object_120.skeleton}
                  />
                  <group name="body_91_correction">
                    <group name="body_91" />
                  </group>
                </group>
              </group>
              <group name="Plane_93" position={[2.7, 4.4, 3.1]} rotation={[0, 0.4, 0]} scale={0.8}>
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.shirt}
                />
              </group>
              <group
                name="headphones_94"
                position={[-3, 4.8, 4.1]}
                rotation={[1.8, 0.1, 0.4]}
                scale={0.3}>
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials['Material.009']}
                />
                <mesh
                  name="Object_125"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials['Material.006']}
                />
                <mesh
                  name="Object_126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group
                name="lamp_95"
                position={[3.1, 4.3, 4.8]}
                rotation={[-Math.PI, 0.7, -Math.PI]}
                scale={0.9}>
                <mesh
                  name="Object_128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials['Material.012']}
                />
                <mesh
                  name="Object_129"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials['Material.003']}
                />
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials['Material.010']}
                />
                <mesh
                  name="Object_131"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials.emission}
                />
              </group>
              <group name="mug_96" position={[-2.1, 4.3, 3.6]} rotation={[0, 1.4, 0]} scale={0.3}>
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials['Material.010']}
                />
                <mesh
                  name="Object_134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={materials['Material.007']}
                />
                <mesh
                  name="Object_135"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group
                name="pencil_97"
                position={[2.6, 4.3, 3.2]}
                rotation={[-Math.PI / 2, Math.PI / 6, Math.PI]}
                scale={[0, 0.3, 0]}>
                <mesh
                  name="Object_137"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials['Material.010']}
                />
                <mesh
                  name="Object_138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={materials['Material.008']}
                />
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials['Material.009']}
                />
              </group>
              <group
                name="phone_98"
                position={[3.6, 4.3, 2.5]}
                rotation={[-Math.PI, -0.2, -Math.PI]}
                scale={0.3}>
                <mesh
                  name="Object_141"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials['Material.009']}
                />
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials['Material.006']}
                />
              </group>
              <group
                name="table_107"
                position={[-0.3, 2.6, 4.2]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-0.1, 1.9, 1.9]}>
                <mesh
                  name="Object_144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials['Material.013']}
                />
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials['Material.004']}
                />
                <group name="Cube001_103" position={[-18.2, 0.6, 0.2]} scale={[0.8, 1, 1]}>
                  <mesh
                    name="Object_147"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_147.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_148"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_148.geometry}
                    material={materials['Material.013']}
                  />
                </group>
                <group name="Cube002_104" position={[-18.2, 0.1, 0.2]} scale={[0.8, 1, 1]}>
                  <mesh
                    name="Object_150"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_151"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_151.geometry}
                    material={materials['Material.013']}
                  />
                </group>
                <group name="Cube004_105" position={[-18.2, -0.4, 0.2]} scale={[0.8, 1, 1]}>
                  <mesh
                    name="Object_153"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_153.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_154"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials['Material.013']}
                  />
                </group>
                <group name="Cube005_106" position={[-18.2, -0.9, 0.2]} scale={[0.8, 1, 1]}>
                  <mesh
                    name="Object_156"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_157"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_157.geometry}
                    material={materials['Material.013']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_man_working_at_a_table_with_a_laptop(1).glb')